[project]
name = "randomizer-pkg"
version = "0.1.0"
description = "Randomizer to show UV workspace"
readme = "README.md"
authors = [
    { name = "Valerio Farrotti", email = "valerio.farrotti@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "staticker-pkg==0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/randomizer_pkg"]

[tool.uv.sources]
randomizer-pkg = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
