[project]
name = "staticker-pkg"
version = "0.1.0"
description = "Staticker to show UV workspace"
readme = "README.md"
authors = [
    { name = "Valerio Farrotti", email = "valerio.farrotti@gmail.com"}
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/staticker_pkg"]
